name: Fernando Mayorga
markdown: kramdown
highlighter: pygments
exclude: [main.scss, config.rb]
description: Personal website de Fernando Mayorga sobre Arte, Historia y Patrimonio
url: http://fernanz.github.io/
gems:
  - octopress-littlefoot 
